###################################################################################
# ⚠️ This file is controlled by OpenTofu in the estate-repos repository.
#    Manual changes will be overwritten the next time OpenTofu runs.
###################################################################################

name: container-build-and-push

on:
  push:
    paths:
      - "disabled"

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  call-workflow:
    uses: evoteum/estate-reusable-workflows/.github/workflows/container-build-and-push.yml@main
    