###################################################################################
# ⚠️ This file is controlled by OpenTofu in the estate-repos repository.
#    Manual changes will be overwritten the next time OpenTofu runs.
#    Last updated: 2025-03-16T21:56:09Z
###################################################################################

name: tofu-apply-all-environments

on:
  workflow_dispatch:
  push:
    paths:
      - "*/**"

permissions:
  actions: write
  contents: write
  id-token: write

jobs:
  call-tofu-apply-all-environments:
    uses: evoteum/estate-reusable-workflows/.github/workflows/tofu-apply-all-environments.yml@main