###################################################################################
# ⚠️ This file is controlled by OpenTofu in the  repository.
#    Manual changes will be overwritten the next time OpenTofu runs.
###################################################################################

name: tofu-apply-all-environments

on:
  push:
    

  



jobs:
  call-tofu-apply-all-environments:
    uses: evoteum/estate-reusable-workflows/.github/workflows/tofu-apply-all-environments.yml@main
    