###################################################################################
# ⚠️ This file is controlled by OpenTofu in the estate-repos repository.
#    Manual changes will be **overwritten** within 24 hours.
###################################################################################

name: tofu-apply

on:
  workflow_dispatch:
  push:
    paths:
      - "tofu/**"

permissions:
  actions: write
  contents: write
  id-token: write

jobs:
  call-tofu-apply:
    uses: evoteum/estate-reusable-workflows/.github/workflows/tofu-apply.yml@main
    secrets: inherit
